// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC37Yt6YT0pOgdUyQUgV5n7LCrqUbhwgzA',
    appId: '1:995233568742:web:8eab53e00d6f59220de827',
    messagingSenderId: '995233568742',
    projectId: 'my-whatsapp-latest',
    authDomain: 'my-whatsapp-latest.firebaseapp.com',
    storageBucket: 'my-whatsapp-latest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrg1KExqFMMbVPJG6_e1cvqStziTTaHSE',
    appId: '1:995233568742:android:154bad491ce07b620de827',
    messagingSenderId: '995233568742',
    projectId: 'my-whatsapp-latest',
    storageBucket: 'my-whatsapp-latest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QDx2F8OyRHOo-nue11WHVytALANJA1M',
    appId: '1:995233568742:ios:80a4c338ba4545940de827',
    messagingSenderId: '995233568742',
    projectId: 'my-whatsapp-latest',
    storageBucket: 'my-whatsapp-latest.firebasestorage.app',
    iosBundleId: 'com.example.myWhatsapp',
  );
}
